package com.apicollabdev.odk.collabdev.enums;


public enum TypeNotification {
    INSCRIPTION, COMMENTAIRE, CREATIONPROJET,
    GAINCOINS, GAINBADGE,DEMANDEPARTICIPATION,
    PROPOSITIONIDEEPROJET,DEMANDECONTRIBUTION,
    DEMADEACCEPTEE, DEMANDEREJETEE, FAIRECONTRIBUTION,
    DEMANDEGESTIONNAIREACCEPTEE, DEMANDEGESTIONNAIREREJETEE,
    CONTRIBUTIONVALIDER, CONTRIBUTIONREJETEE, FONCTIONNALITERESERVE,
    DEMANDEGESTIONNAIRE, FONCTIONNALITEAJOUTER, FONCTIONNALITETERMINEE,
    RESERVEFONCTIONNALITE, AJOUTERCONTRIBUTION, CONTRIBUTIONAJOUTER,
    AJOUTERFONCTIONNALITE

}

