package com.apicollabdev.odk.collabdev.enums;


public enum TypeNotification {
    INSCRIPTION, COMMENTAIRE,
    GAINCOINS, GAINBADGE,DEMANDEPARTICIPATION,
    PROPOSITIONIDEEPROJET,DEMANDECONTRIBUTION,
    DEMADEACCEPTEE, DEMANDEREJETEE,
    DEMANDEGESTIONNAIREACCEPTEE, DEMANDEGESTIONNAIREREJETEE,
    DEMANDEGESTIONNAIRE
}

